
@host=http://localhost/
@api=api/auth
@jwt_tokken=secret
@search_res_name=Drive Thru Eatin'
@search_res_id=4Zh2DxFItLoBYQiNeMhP
@search_res_array=name,DriveThur
@new_res_name=MC Donald
@new_res_photo=https://storage.googleapis.com/firestorequickstarts.appspot.com/food_12.png
@new_res_avgRating=0
@new_res_category=Italian
@new_res_city=Los Angeles
@new_res_price=2
@new_res_name=Prime Eatin'
@new_res_numRatings=0

@update_res_name=MC Donald
@update_res_photo=https://storage.googleapis.com/firestorequickstarts.appspot.com/food_12.png
@update_res_avgRating=0
@update_res_category=Indian
@update_res_city=Los Angeles
@update_res_price=3
@update_res_name=Prime Eatin'
@update_res_numRatings=0


GET {{host}}{{api}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{jwt_tokken}}
//API STATUS
###


//GET ALL RESTAURANTS
GET {{host}}{{api}}/data HTTP/1.1
content-type: application/json
Authorization: Bearer {{jwt_tokken}}
//API ALL
###


//GET RESTURANT BY ID
GET {{host}}{{api}}/data/{{search_res_id}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{jwt_tokken}}
//API FIND ONE BY NAME
###
GET {{host}}{{api}}/data/?id={{search_res_id}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{jwt_tokken}}
//API FIND ONE BY NAME
###
GET {{host}}{{api}}/data HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{jwt_tokken}}

id={{search_res_id}}
//API FIND ONE BY NAME
###


//GET RESTAURANTS SEARCH
GET {{host}}{{api}}/data/search HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{jwt_tokken}}

name={{search_res_name}}
&category={{new_res_category}}
//API SEARCH BY FILTER
###

GET {{host}}{{api}}/data/search/{{search_res_name}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{jwt_tokken}}
//API FIND ONE BY EMAIL
###

GET {{host}}{{api}}/data/search/?name={{search_res_name}}&city={{new_res_city}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{jwt_tokken}}
//API FIND ONE BY EMAIL
###


//POST RESTAURANT
POST {{host}}{{api}}/data/?name={{new_res_name}}&photo={{new_res_photo}}&avgRating={{new_res_avgRating}}&category={{new_res_category}}&city={{new_res_city}}&price={{new_res_price}}&numRatings={{new_res_numRatings}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{jwt_tokken}}
//API CREATE USER
###

POST {{host}}{{api}}/data/ HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{jwt_tokken}}

name={{new_res_name}}
&photo={{new_res_photo}}
&avgRating={{new_res_avgRating}}
&category={{new_res_category}}
&city={{new_res_city}}
&price={{new_res_price}}
&numRatings={{new_res_numRatings}}
//API CREATE USER
###


DELETE  {{host}}{{api}}/data/4Zh2DxFItLoBYQiNeMhP HTTP/1.1
content-type: application/json
Authorization: Bearer {{jwt_tokken}}
//API DELETE USER BY ID
###

DELETE  {{host}}{{api}}/data/?id=KIxWTiWLyhOZovdeAteR HTTP/1.1
content-type: application/json
Authorization: Bearer {{jwt_tokken}}
//API DELETE USER BY ID
###

DELETE  {{host}}{{api}}/data/ HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{jwt_tokken}}

id=LbBzj2j9AVUwHHgSI7Pn
###


PATCH  {{host}}{{api}}/data/ HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{jwt_tokken}}

id=D6pi6y7vtcMvcUPS3duR
&name={{update_res_name}}
&photo={{update_res_photo}}
&avgRating={{update_res_avgRating}}
&category={{update_res_category}}
&city={{update_res_city}}
&price={{update_res_price}}
&numRatings={{update_res_numRatings}}
//API UPDATE USER
###

PATCH  {{host}}{{api}}/data/ratings/?resId=ipZWLzHfu13iWZoO20b0&rating=2&text=Updated Rating&userId=tzr5z45ghfhcvkhtlrsg&userName=Updated UserName HTTP/1.1
content-type: application/json
Authorization: Bearer {{jwt_tokken}}
//API UPDATE USER
###
PATCH  {{host}}{{api}}/data/ratings HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{jwt_tokken}}

resId=ipZWLzHfu13iWZoO20b0
&rateId=KLdEwgt5j0M3sKIGY8k
&rating=1
&text=Updated Rating
&userId=tzr5z45ghfhcvkhtlrsg
&userName=Updated UserName
//API UPDATE USER
###

PATCH  {{host}}{{api}}/data/?id=4Zh2DxFItLoBYQiNeMhP&price={{update_res_price}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{jwt_tokken}}
//API UPDATE USER
###


POST {{host}}{{api}}/data/ratings/?resId=ipZWLzHfu13iWZoO20b0&rateId=KLdEwgt5j0M3sKIGY8k&rating=2&text=Updated Rating&userId=tzr5z45ghfhcvkhtlrsg&userName=Updated UserName HTTP/1.1
content-type: application/json
Authorization: Bearer {{jwt_tokken}}
//API CREATE USER
###

POST {{host}}{{api}}/data/ratings HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{jwt_tokken}}

resId=ipZWLzHfu13iWZoO20b0
&rateId=KLdEwgt5j0M3sKIGY8k
&rating=2
&text=Updated Rating
&userId=tzr5z45ghfhcvkhtlrsg
&userName=Updated UserName

//API CREATE USER
###
