@host=http://localhost/
@api=api/mongo
@jwt_tokken=Secret
@search_user_id=5f7b40e4f869f56cdce09ad8
@search_title=Douglas Adams
@search_name=MacKenzie Patel
@search_email=adipiscing.elit.aliquam@donecegestasaliquam.com


@new_author_name=New Author
@new_author_age=78
@new_fan_email=author@example.de
@new_fan_name=New Fan
@new_story_title=New Story


@update_author_name=Solomon Mcgowan22
@update_new_author_name=Solomon Mcgowan
@update_author_age=10
@update_fan_email=author@example.de
@update_new_fan_email=author2@example.de
@update_fan_name=New Fan
@update_story_title=Douglas Adams
@update_new_story_title=Douglas Adams


//GET ALL USERS
GET {{host}}{{api}}/stories HTTP/1.1
content-type: application/json
Authorization: Bearer {{jwt_tokken}}
//API ALL USERS
###

//GET USER ID
GET {{host}}{{api}}/stories/{{search_user_id}} HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{jwt_tokken}}
###
GET {{host}}{{api}}/stories/?id={{search_user_id}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{jwt_tokken}}
###
GET {{host}}{{api}}/stories/ HTTP/1.1
content-type: application/x-www-form-urlencoded
Authorization: Bearer {{jwt_tokken}}

id={{search_user_id}}
###

//GET USER BY EMAIL

GET {{host}}{{api}}/stories/search/{{search_title}} HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{jwt_tokken}}
###
GET {{host}}{{api}}/stories/search/?title={{search_title}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{jwt_tokken}}
###
GET {{host}}{{api}}/stories/search HTTP/1.1
content-type: application/x-www-form-urlencoded
Authorization: Bearer {{jwt_tokken}}

title={{search_title}}
###

//POST USER
POST {{host}}{{api}}/stories HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{jwt_tokken}}

story_title={{new_story_title}}
###

POST {{host}}{{api}}/stories/?story_title={{new_story_title}}  HTTP/1.1
content-type: application/json
Authorization: Bearer {{jwt_tokken}}

###


//DELETE USER
DELETE {{host}}{{api}}/stories/{{new_story_title}} HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{jwt_tokken}}
###
DELETE {{host}}{{api}}/stories/?story_title={{new_story_title}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{jwt_tokken}}
###
DELETE {{host}}{{api}}/stories HTTP/1.1
content-type: application/x-www-form-urlencoded
Authorization: Bearer {{jwt_tokken}}

story_title={{new_story_title}}
###

//UPDATE USER
PATCH {{host}}{{api}}/stories/?story_title={{update_story_title}}&new_story_title={{update_new_story_title}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{jwt_tokken}}
###

PATCH {{host}}{{api}}/stories HTTP/1.1
content-type: application/x-www-form-urlencoded
Authorization: Bearer {{jwt_tokken}}

story_title={{update_story_title}}
&new_story_title={{update_new_story_title}}
###
