@host=http://localhost/
@api=api/mongo
@jwt_tokken=Secret
@search_user_id=5f7b40e4f869f56cdce09ad6
@search_title=Douglas Adams
@search_name=MacKenzie Patel
@search_email=adipiscing.elit.aliquam@donecegestasaliquam.com


@new_author_name=New Author
@new_author_age=78
@new_fan_email=author@example.de
@new_fan_name=New Fan
@new_story_title=New Story


@update_author_name=Solomon Mcgowan22
@update_new_author_name=Solomon Mcgowan
@update_author_age=10
@update_fan_email=hendrerit@loremluctusut.org
@update_new_fan_email=hendrerit@loremluctusut.org
@update_fan_name=Rebekah Mueller Updated
@update_story_title=New Story
@update_new_story_title=New Story2






//GET ALL USERS
GET {{host}}{{api}}/fans HTTP/1.1
content-type: application/json
Authorization: Bearer {{jwt_tokken}}
//API ALL USERS
###

//GET USER ID
GET {{host}}{{api}}/fans/{{search_user_id}} HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{jwt_tokken}}
###
GET {{host}}{{api}}/fans/?id={{search_user_id}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{jwt_tokken}}
###
GET {{host}}{{api}}/fans/ HTTP/1.1
content-type: application/x-www-form-urlencoded
Authorization: Bearer {{jwt_tokken}}

id={{search_user_id}}
###

//GET USER BY EMAIL

GET {{host}}{{api}}/fans/search/{{search_email}} HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{jwt_tokken}}
###
GET {{host}}{{api}}/fans/search/?email={{search_email}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{jwt_tokken}}
###
GET {{host}}{{api}}/fans/search HTTP/1.1
content-type: application/x-www-form-urlencoded
Authorization: Bearer {{jwt_tokken}}

email={{search_email}}
###

//POST USER
POST {{host}}{{api}}/fans HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{jwt_tokken}}

fan_email={{new_fan_email}}
&fan_name={{new_fan_name}}
###

POST {{host}}{{api}}/fans/?fan_email={{new_fan_email}}&fan_name={{new_fan_name}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{jwt_tokken}}

###


//DELETE USER
DELETE {{host}}{{api}}/fans/{{new_fan_email}} HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{jwt_tokken}}
###
DELETE {{host}}{{api}}/fans/?fan_email={{new_fan_email}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{jwt_tokken}}
###
DELETE {{host}}{{api}}/fans HTTP/1.1
content-type: application/x-www-form-urlencoded
Authorization: Bearer {{jwt_tokken}}

fan_email={{new_fan_email}}
###

//UPDATE USER
PATCH {{host}}{{api}}/fans/?fan_email={{update_fan_email}}&new_fan_email={{update_new_fan_email}}&fan_name={{update_fan_name}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{jwt_tokken}}
###
PATCH {{host}}{{api}}/fans HTTP/1.1
content-type: application/x-www-form-urlencoded
Authorization: Bearer {{jwt_tokken}}

fan_email={{update_fan_email}}
&new_fan_email={{update_new_fan_email}}
&fan_name={{update_fan_name}}
###
