# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    container_name: mongoDB
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: public
    volumes:
      - ./init/init.js:/docker-entrypoint-initdb.d/init.js

    networks:
      dh-bridge:
        ipv4_address: 172.29.0.6
    ports:
      - 27501:27017
  mongo-express:
    container_name: mongoExpress
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      dh-bridge:
        ipv4_address: 172.29.0.7
networks:
  dh-bridge:
    external: true
