@host=http://localhost/
@api=api/json-users
@jwt_tokken=Secret
@search_user_id=3
@search_displayName=Deborah Ochoa
@search_email=nunc.ut.erat@classaptenttaciti.co.uk

@new_email=user@example.de
@new_password=password
@new_emailVerified=false
@new_displayName=Deborah Ochoa
@new_photoUrl=http://www.host/photo.jpg
@new_phoneNumber=+449956933282
@new_disabled=false

@update_email=update@example.de
@update_password=update_password
@update_emailVerified=true
@update_displayName=update update
@update_photoUrl=http://www.host/update.jpg
@update_phoneNumber=+133756933282
@update_disabled=ture

//GET ALL USERS
GET {{host}}{{api}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{jwt_tokken}}
//API ALL USERS
###

//GET USER ID
GET {{host}}{{api}}/{{search_user_id}} HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{jwt_tokken}}
###
GET {{host}}{{api}}/?id={{search_user_id}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{jwt_tokken}}
###
GET {{host}}{{api}} HTTP/1.1
content-type: application/x-www-form-urlencoded
Authorization: Bearer {{jwt_tokken}}

id={{search_user_id}}
###

//GET USER BY EMAIL

GET {{host}}{{api}}/search/{{search_email}} HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{jwt_tokken}}
###
GET {{host}}{{api}}/search/?email={{search_email}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{jwt_tokken}}
###
GET {{host}}{{api}}/search HTTP/1.1
content-type: application/x-www-form-urlencoded
Authorization: Bearer {{jwt_tokken}}

email={{search_email}}
###

//POST USER
POST {{host}}{{api}} HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{jwt_tokken}}

email={{new_email}}
&password={{new_password}}
&emailVerified={{new_emailVerified}}
&displayName={{new_displayName}}
&photoUrl={{new_photoUrl}}
&phoneNumber={{new_phoneNumber}}
&disabled={{new_disabled}}
###

POST {{host}}{{api}}/?email={{new_email}}&password={{new_password}}&emailVerified={{new_emailVerified}}&displayName={{new_displayName}}&photoUrl={{new_photoUrl}}&phoneNumber={{new_phoneNumber}}&disabled={{new_disabled}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{jwt_tokken}}

###


//DELETE USER
DELETE {{host}}{{api}}/{{new_email}} HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{jwt_tokken}}
###
DELETE {{host}}{{api}}/?email={{new_email}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{jwt_tokken}}
###
DELETE {{host}}{{api}} HTTP/1.1
content-type: application/x-www-form-urlencoded
Authorization: Bearer {{jwt_tokken}}

email={{new_email}}
###

//UPDATE USER
PATCH {{host}}{{api}}/?search_email={{new_email}}&email={{update_email}}&password={{update_password}}&emailVerified={{update_emailVerified}}&displayName={{update_displayName}}&photoUrl={{update_photoUrl}}&phoneNumber={{update_phoneNumber}}&disabled={{update_disabled}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{jwt_tokken}}
###
PATCH {{host}}{{api}} HTTP/1.1
content-type: application/x-www-form-urlencoded
Authorization: Bearer {{jwt_tokken}}

search_email={{new_email}}
&email={{update_email}}
&password={{update_password}}
&emailVerified={{update_emailVerified}}
&displayName={{update_displayName}}
&photoUrl={{update_photoUrl}}
&phoneNumber={{update_phoneNumber}}
&disabled={{update_disabled}}
###
